security:
    # Gestion des hasheurs de mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Chargement des utilisateurs (providers)
    providers:
        # Recharge l'utilisateur à partir de la session, et autres fonctionnalités
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        # Désactive la sécurité pour les routes internes comme le profiler
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            # Authenticator personnalisé
            custom_authenticator: App\Security\LoginFormAuthenticator

            # Point d'entrée pour l'authentification
            entry_point: App\Security\LoginFormAuthenticator

            # Configuration pour le formulaire de connexion (non utilisée avec un custom authenticator, mais utile en fallback)
            form_login:
                login_path: app_login
                check_path: app_login

            # Configuration pour la déconnexion
            logout:
                path: app_logout
                target: /

            # Fonctionnalité "Se souvenir de moi"
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 7 jours
                path: /
                # Décommentez la ligne suivante pour activer systématiquement "Se souvenir de moi"
                #always_remember_me: true

    # Contrôle d'accès (règles pour les rôles et les chemins)
    access_control:
        # Exemple : accès uniquement pour les admins
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # Exemple : accès pour les utilisateurs connectés
        # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            # Réduction des coûts de hash pour accélérer les tests
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Valeur minimale pour bcrypt
                time_cost: 3 # Valeur minimale pour argon
                memory_cost: 10 # Valeur minimale pour argon
